2025-04-23 10:47:57,247 ERROR: Error in generate: list index out of range [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:483]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 195, in generate
    SIG_REVIEW_TECH    = build_sig_images([PRE_APPROVALS[1]])[0]
                                           ~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-04-23 11:25:05,670 ERROR: Error in generate: list index out of range [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:483]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 195, in generate
    for appr in approvals:
    
IndexError: list index out of range
2025-04-23 11:28:27,163 INFO: SAT Report Generator startup [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\app.py:38]
2025-04-23 11:29:07,493 ERROR: Error in generate: list index out of range [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:514]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 226, in generate
    SIG_REVIEW_TECH    = build_sig_images([PRE_APPROVALS[1]])[0]
                                           ~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-04-23 11:45:57,814 INFO: SAT Report Generator startup [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\app.py:38]
2025-04-23 11:46:13,534 ERROR: Error in generate: list index out of range [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:529]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 241, in generate
    SIG_REVIEW_TECH    = build_sig_images([PRE_APPROVALS[1]])[0]
                                           ~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-04-23 11:48:47,530 ERROR: Error in generate: list index out of range [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:529]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 241, in generate
IndexError: list index out of range
2025-04-23 11:50:41,717 ERROR: Error in generate: list index out of range [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:529]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 241, in generate
IndexError: list index out of range
2025-04-23 11:55:14,912 INFO: SAT Report Generator startup [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\app.py:38]
2025-04-23 11:55:37,424 WARNING: Could not autofit tables: 'in <string>' requires string as left operand, not ellipsis [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:495]
2025-04-23 11:55:40,037 INFO: Approval email sent to revanthmeda7702@gmail.com [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:515]
2025-04-23 11:55:40,049 INFO: Generated report for submission 937fca77-b984-4ef6-8e70-b6eec602096b [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:526]
2025-04-23 12:05:35,529 INFO: SAT Report Generator startup [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\app.py:38]
2025-04-23 12:06:43,412 WARNING: Could not autofit tables: 'in <string>' requires string as left operand, not ellipsis [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:512]
2025-04-23 12:06:45,588 INFO: Approval email sent to revanthmeda7702@gmail.com [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:532]
2025-04-23 12:06:45,604 INFO: Generated report for submission 44bd1e93-a120-4a9c-b32f-7724d7befcbb [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:543]
2025-04-23 12:17:33,574 INFO: SAT Report Generator startup [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\app.py:38]
2025-04-23 12:18:26,766 WARNING: Could not autofit tables: 'in <string>' requires string as left operand, not ellipsis [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:512]
2025-04-23 12:18:28,872 INFO: Approval email sent to revanthmeda7702@gmail.com [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:532]
2025-04-23 12:18:28,888 INFO: Generated report for submission df0cde00-f89b-4e2b-a6f7-5c97714c1be1 [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:543]
2025-04-23 12:39:51,494 INFO: SAT Report Generator startup [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\app.py:38]
2025-04-23 12:40:05,770 ERROR: Error in generate: name 'is_final_approval' is not defined [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:589]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 110, in generate
    if is_final_approval:
       ^^^^^^^^^^^^^^^^^
NameError: name 'is_final_approval' is not defined
2025-04-23 12:41:21,958 ERROR: Error in generate: name 'is_final_approval' is not defined [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:589]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 110, in generate
    sig_data_url = request.form.get("sig_prepared_data", "")
       ^^^^^^^^^^^^^^^^^
NameError: name 'is_final_approval' is not defined
2025-04-23 12:43:13,039 ERROR: Error in generate: name 'is_final_approval' is not defined [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:589]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 110, in generate
    # ---- START remove everything from here ----
NameError: name 'is_final_approval' is not defined
2025-04-23 12:44:21,789 ERROR: Error in generate: name 'is_final_approval' is not defined [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:589]
Traceback (most recent call last):
  File "C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py", line 110, in generate
    # ---- START remove everything from here ----
NameError: name 'is_final_approval' is not defined
2025-04-23 12:45:31,829 INFO: SAT Report Generator startup [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\app.py:38]
2025-04-23 12:45:51,417 WARNING: Could not autofit tables: 'in <string>' requires string as left operand, not ellipsis [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:511]
2025-04-23 12:45:53,516 INFO: Approval email sent to revanthmeda7702@gmail.com [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:531]
2025-04-23 12:45:53,531 INFO: Generated report for submission 3e492022-40d2-4cdc-858a-504334552385 [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:542]
2025-04-23 12:50:33,095 INFO: SAT Report Generator startup [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\app.py:38]
2025-04-23 12:50:58,089 WARNING: Could not autofit tables: 'in <string>' requires string as left operand, not ellipsis [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:511]
2025-04-23 12:51:01,484 INFO: Approval email sent to revanthmeda7702@gmail.com [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:531]
2025-04-23 12:51:01,500 INFO: Generated report for submission 83fb0485-6fe8-49b8-b41f-d373c9903d86 [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:542]
2025-04-23 12:57:39,452 WARNING: Could not autofit tables: 'in <string>' requires string as left operand, not ellipsis [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:511]
2025-04-23 12:57:43,057 INFO: Approval email sent to revanthmeda7702@gmail.com [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:531]
2025-04-23 12:57:43,075 INFO: Generated report for submission 5eefc99b-f642-4e48-bf76-6fed92ba8724 [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:542]
2025-04-23 13:03:46,842 INFO: SAT Report Generator startup [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\app.py:38]
2025-04-23 13:04:24,842 WARNING: Could not autofit tables: 'in <string>' requires string as left operand, not ellipsis [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:511]
2025-04-23 13:04:27,230 INFO: Approval email sent to revanthmeda7702@gmail.com [in C:\Users\rmeda\OneDrive - CULLY AUTOMATION\Personal\Automate SAT\SAT_Report_App\routes\main.py:531]
