PS E:\report generator\WORKINGCULLY (1)\WORKINGCULLY> python app.py
🔧 Initializing SAT Report Generator...
C:\Program Files\Python312\Lib\site-packages\docxcompose\properties.py:18: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
🚀 Starting SAT Report Generator...
Debug Mode: False
Running on http://0.0.0.0:5000
✅ Required directories created successfully
🌐 Health check endpoint available at /health
 * Serving Flask app 'app'
 * Debug mode: off
INFO:werkzeug:←[31m←[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.←[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.18.21:5000
INFO:werkzeug:←[33mPress CTRL+C to quit←[0m
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:11] "←[32mGET / HTTP/1.1←[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:11] "GET /auth/welcome HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:11] "←[36mGET /static/css/form.css HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:11] "←[36mGET /static/cully.png HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:12] "←[33mGET /favicon.ico HTTP/1.1←[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:14] "GET /auth/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:14] "←[36mGET /static/css/form.css HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:15] "←[36mGET /static/cully.png HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:17] "←[32mPOST /auth/login HTTP/1.1←[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:17] "GET /dashboard/engineer HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:18] "←[36mGET /static/css/form.css HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:18] "←[36mGET /static/cully.png HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:20] "GET /reports/new HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:20] "←[36mGET /static/css/form.css HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:20] "←[36mGET /static/cully.png HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:20] "GET /dashboard/db-status HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:21] "GET /reports/new/sat/full HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:22] "←[36mGET /static/css/form.css HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:22] "←[36mGET /static/cully.png HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:22] "←[36mGET /static/Cully_Watermark.jpg HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:22] "←[36mGET /static/js/form.js HTTP/1.1←[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:23] "GET /api/get-users-by-role HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:22:23] "←[33mGET /static/img/favicon.ico HTTP/1.1←[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:25:41] "GET /refresh_csrf HTTP/1.1" 200 -
send: 'ehlo Cullyaz-dev2022.ad.cullyautomation.net\r\n'
reply: b'250-smtp.gmail.com at your service, [52.169.156.168]\r\n'
reply: b'250-SIZE 35882577\r\n'
reply: b'250-8BITMIME\r\n'
reply: b'250-STARTTLS\r\n'
reply: b'250-ENHANCEDSTATUSCODES\r\n'
reply: b'250-PIPELINING\r\n'
reply: b'250-CHUNKING\r\n'
reply: b'250 SMTPUTF8\r\n'
reply: retcode (250); Msg: b'smtp.gmail.com at your service, [52.169.156.168]\nSIZE 35882577\n8BITMIME\nSTARTTLS\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'
send: 'STARTTLS\r\n'
reply: b'220 2.0.0 Ready to start TLS\r\n'
reply: retcode (220); Msg: b'2.0.0 Ready to start TLS'
send: 'ehlo Cullyaz-dev2022.ad.cullyautomation.net\r\n'
reply: b'250-smtp.gmail.com at your service, [52.169.156.168]\r\n'
reply: b'250-SIZE 35882577\r\n'
reply: b'250-8BITMIME\r\n'
reply: b'250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\r\n'
reply: b'250-ENHANCEDSTATUSCODES\r\n'
reply: b'250-PIPELINING\r\n'
reply: b'250-CHUNKING\r\n'
reply: b'250 SMTPUTF8\r\n'
reply: retcode (250); Msg: b'smtp.gmail.com at your service, [52.169.156.168]\nSIZE 35882577\n8BITMIME\nAUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'
send: 'AUTH PLAIN AG1lZGEucmV2YW50aEBnbWFpbC5jb20AcnFyY2JhbmpydXVjaGp2bQ==\r\n'
reply: b'535-5.7.8 Username and Password not accepted. For more information, go to\r\n'
reply: b'535 5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45cb6e44373sm2946425e9.3 - gsmtp\r\n'
reply: retcode (535); Msg: b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45cb6e44373sm2946425e9.3 - gsmtp'
send: 'AUTH LOGIN bWVkYS5yZXZhbnRoQGdtYWlsLmNvbQ==\r\n'
reply: b'334 UGFzc3dvcmQ6\r\n'
reply: retcode (334); Msg: b'UGFzc3dvcmQ6'
send: 'cnFyY2JhbmpydXVjaGp2bQ==\r\n'
reply: b'535-5.7.8 Username and Password not accepted. For more information, go to\r\n'
reply: b'535 5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45cb6e44373sm2946425e9.3 - gsmtp\r\n'
reply: retcode (535); Msg: b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45cb6e44373sm2946425e9.3 - gsmtp'
send: 'QUIT\r\n'
reply: b'221 2.0.0 closing connection 5b1f17b1804b1-45cb6e44373sm2946425e9.3 - gsmtp\r\n'
reply: retcode (221); Msg: b'2.0.0 closing connection 5b1f17b1804b1-45cb6e44373sm2946425e9.3 - gsmtp'
ERROR:utils:Email attempt 1/3 failed: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45cb6e44373sm2946425e9.3 - gsmtp')
Traceback (most recent call last):
  File "E:\report generator\WORKINGCULLY (1)\WORKINGCULLY\utils.py", line 372, in send_email
    server.login(smtp_username, smtp_password)
  File "C:\Program Files\Python312\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Program Files\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45cb6e44373sm2946425e9.3 - gsmtp')
send: 'ehlo Cullyaz-dev2022.ad.cullyautomation.net\r\n'
reply: b'250-smtp.gmail.com at your service, [52.169.156.168]\r\n'
reply: b'250-SIZE 35882577\r\n'
reply: b'250-8BITMIME\r\n'
reply: b'250-STARTTLS\r\n'
reply: b'250-ENHANCEDSTATUSCODES\r\n'
reply: b'250-PIPELINING\r\n'
reply: b'250-CHUNKING\r\n'
reply: b'250 SMTPUTF8\r\n'
reply: retcode (250); Msg: b'smtp.gmail.com at your service, [52.169.156.168]\nSIZE 35882577\n8BITMIME\nSTARTTLS\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'
send: 'STARTTLS\r\n'
reply: b'220 2.0.0 Ready to start TLS\r\n'
reply: retcode (220); Msg: b'2.0.0 Ready to start TLS'
send: 'ehlo Cullyaz-dev2022.ad.cullyautomation.net\r\n'
reply: b'250-smtp.gmail.com at your service, [52.169.156.168]\r\n'
reply: b'250-SIZE 35882577\r\n'
reply: b'250-8BITMIME\r\n'
reply: b'250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\r\n'
reply: b'250-ENHANCEDSTATUSCODES\r\n'
reply: b'250-PIPELINING\r\n'
reply: b'250-CHUNKING\r\n'
reply: b'250 SMTPUTF8\r\n'
reply: retcode (250); Msg: b'smtp.gmail.com at your service, [52.169.156.168]\nSIZE 35882577\n8BITMIME\nAUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'
send: 'AUTH PLAIN AG1lZGEucmV2YW50aEBnbWFpbC5jb20AcnFyY2JhbmpydXVjaGp2bQ==\r\n'
reply: b'535-5.7.8 Username and Password not accepted. For more information, go to\r\n'
reply: b'535 5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b7e380b77sm236634805e9.11 - gsmtp\r\n'
reply: retcode (535); Msg: b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b7e380b77sm236634805e9.11 - gsmtp'
send: 'AUTH LOGIN bWVkYS5yZXZhbnRoQGdtYWlsLmNvbQ==\r\n'
reply: b'334 UGFzc3dvcmQ6\r\n'
reply: retcode (334); Msg: b'UGFzc3dvcmQ6'
send: 'cnFyY2JhbmpydXVjaGp2bQ==\r\n'
reply: b'535-5.7.8 Username and Password not accepted. For more information, go to\r\n'
reply: b'535 5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b7e380b77sm236634805e9.11 - gsmtp\r\n'
reply: retcode (535); Msg: b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b7e380b77sm236634805e9.11 - gsmtp'
send: 'QUIT\r\n'
reply: b'221 2.0.0 closing connection 5b1f17b1804b1-45b7e380b77sm236634805e9.11 - gsmtp\r\n'
reply: retcode (221); Msg: b'2.0.0 closing connection 5b1f17b1804b1-45b7e380b77sm236634805e9.11 - gsmtp'
ERROR:utils:Email attempt 2/3 failed: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b7e380b77sm236634805e9.11 - gsmtp')
Traceback (most recent call last):
  File "E:\report generator\WORKINGCULLY (1)\WORKINGCULLY\utils.py", line 372, in send_email
    server.login(smtp_username, smtp_password)
  File "C:\Program Files\Python312\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Program Files\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b7e380b77sm236634805e9.11 - gsmtp')
send: 'ehlo Cullyaz-dev2022.ad.cullyautomation.net\r\n'
reply: b'250-smtp.gmail.com at your service, [52.169.156.168]\r\n'
reply: b'250-SIZE 35882577\r\n'
reply: b'250-8BITMIME\r\n'
reply: b'250-STARTTLS\r\n'
reply: b'250-ENHANCEDSTATUSCODES\r\n'
reply: b'250-PIPELINING\r\n'
reply: b'250-CHUNKING\r\n'
reply: b'250 SMTPUTF8\r\n'
reply: retcode (250); Msg: b'smtp.gmail.com at your service, [52.169.156.168]\nSIZE 35882577\n8BITMIME\nSTARTTLS\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'
send: 'STARTTLS\r\n'
reply: b'220 2.0.0 Ready to start TLS\r\n'
reply: retcode (220); Msg: b'2.0.0 Ready to start TLS'
send: 'ehlo Cullyaz-dev2022.ad.cullyautomation.net\r\n'
reply: b'250-smtp.gmail.com at your service, [52.169.156.168]\r\n'
reply: b'250-SIZE 35882577\r\n'
reply: b'250-8BITMIME\r\n'
reply: b'250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\r\n'
reply: b'250-ENHANCEDSTATUSCODES\r\n'
reply: b'250-PIPELINING\r\n'
reply: b'250-CHUNKING\r\n'
reply: b'250 SMTPUTF8\r\n'
reply: retcode (250); Msg: b'smtp.gmail.com at your service, [52.169.156.168]\nSIZE 35882577\n8BITMIME\nAUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8'
send: 'AUTH PLAIN AG1lZGEucmV2YW50aEBnbWFpbC5jb20AcnFyY2JhbmpydXVjaGp2bQ==\r\n'
reply: b'535-5.7.8 Username and Password not accepted. For more information, go to\r\n'
reply: b'535 5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b99f6923dsm32032655e9.0 - gsmtp\r\n'
reply: retcode (535); Msg: b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b99f6923dsm32032655e9.0 - gsmtp'
send: 'AUTH LOGIN bWVkYS5yZXZhbnRoQGdtYWlsLmNvbQ==\r\n'
reply: b'334 UGFzc3dvcmQ6\r\n'
reply: retcode (334); Msg: b'UGFzc3dvcmQ6'
send: 'cnFyY2JhbmpydXVjaGp2bQ==\r\n'
reply: b'535-5.7.8 Username and Password not accepted. For more information, go to\r\n'
reply: b'535 5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b99f6923dsm32032655e9.0 - gsmtp\r\n'
reply: retcode (535); Msg: b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b99f6923dsm32032655e9.0 - gsmtp'
send: 'QUIT\r\n'
reply: b'221 2.0.0 closing connection 5b1f17b1804b1-45b99f6923dsm32032655e9.0 - gsmtp\r\n'
reply: retcode (221); Msg: b'2.0.0 closing connection 5b1f17b1804b1-45b99f6923dsm32032655e9.0 - gsmtp'
ERROR:utils:Email attempt 3/3 failed: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b99f6923dsm32032655e9.0 - gsmtp')
Traceback (most recent call last):
  File "E:\report generator\WORKINGCULLY (1)\WORKINGCULLY\utils.py", line 372, in send_email
    server.login(smtp_username, smtp_password)
  File "C:\Program Files\Python312\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Program Files\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-45b99f6923dsm32032655e9.0 - gsmtp')
Would send edit link to rmeda@cully.ie: 19890bcf-9093-4e33-9079-465e3888d2d8
INFO:werkzeug:127.0.0.1 - - [03/Sep/2025 09:25:48] "POST /generate HTTP/1.1" 200 -